image:
  # -- java-app image
  full: nufusrufus/devops-interview-app:c3ded375aee8a592b8ce08a9bd6024285e6765e6
  # -- java-app image pull policy
  pullPolicy: IfNotPresent

podSecurityContext:
  # -- User ID for the container
  runAsUser: 1000
  # -- GID for the container
  runAsGroup: 101
  # -- group for the container
  fsGroup: 101

securityContext:
  # -- Container child process can gain more privileges than its parent
  allowPrivilegeEscalation: false
  runAsNonRoot: true

service:
  # -- Kubernetes Service type
  type: ClusterIP
  ports:
    # -- java-app service http port
    http: 8080
    # -- java-app service monitoring port
    monitoring: 8081

containerPorts:
  # -- java-app container http server port
  http: 8080

authorization:
  # -- username for login
  username: "admin"
  # -- password for login
  password: "pass"

statefulset:
  updateStrategy:
    # -- Update Strategy Type for java-app
    type: RollingUpdate
  # -- Pod Management Policy for statefulset
  podManagementPolicy: Parallel
  # -- java-app replicas
  replicaCount: 2

persistence:
  ## -- mount path for file
  mountPath: /home/javauser/data
  ## -- access Modes
  accessModes: [ "ReadWriteOnce" ]
  # -- size for PVC
  size: 256M

resources:
  requests:
    # -- The requested memory for the container
    memory: "256Mi"
    # -- The requested cpu for the container
    cpu: "500m"
  limits:
    # -- The memory limit for the container
    memory: "512Mi"

# -- Map of annotations to add to the pods
podAnnotations: {}

# -- Node labels for manager pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

tolerations: []

# -- Affinity for manager pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
