apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.authorization.username | b64enc | quote }}
  password: {{ .Values.authorization.password | b64enc | quote }}
