apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "java-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicaCount }}
  serviceName: {{ template "java-app.fullname" . }}-headless
  podManagementPolicy: {{ .Values.statefulset.podManagementPolicy }}
  {{- if .Values.statefulset.updateStrategy }}
  updateStrategy: {{- toYaml .Values.statefulset.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "java-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "java-app.selectorLabels" . | nindent 8 }}
        logType: "java"
        app: {{ template "java-app.name" . }}
        release: {{ .Release.Name }}
        logging: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            - name: monitoring
              containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "{{ .Values.containerPorts.http }}"
            - name: APPLICATION_FILE_PATH
              value: "{{ .Values.persistence.mountPath }}/devops-dummy-app-access.txt"
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "java-app.fullname" . }}
                  key: username
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "java-app.fullname" . }}
                  key: password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: monitoring
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: monitoring
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: visits
              mountPath: {{ .Values.persistence.mountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: visits
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
